create proc bai2_1 @MANV varchar (3)
as
begin
	select * from NHANVIEN where MANV = @MANV
end

exec bai2_1 '002'

select COUNT(MANV) as 'SoLuong' ,MADA ,TENPHG from NHANVIEN
inner join PHONGBAN on NHANVIEN.PHG = PHONGBAN.MAPHG
inner join DEAN on DEAN.PHONG = PHONGBAN.MAPHG
where MADA = 2 and DDIEM_DA = 'Nha Trang '
group by TENPHG,MADA

alter proc bai2_2 @manv int
as
begin
	select COUNT(MANV) as 'so luong' ,MADA ,TENPHG from NHANVIEN
	inner join PHONGBAN on NHANVIEN.PHG = PHONGBAN.MAPHG
	inner join DEAN on DEAN.PHONG = PHONGBAN.MAPHG
	where MADA = @manv
	group by TENPHG,MADA
end

exec bai2_2 1
/* Bài 2-4 */

create proc bai2_4 @MaTP varchar(5)
as
begin 
	select HONV, TENNV, TENPHG, NHANVIEN.MANV, THANNHAN.* FROM NHANVIEN
	inner join PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
	left outer join THANNHAN on THANNHAN.MA_NVIEN = NHANVIEN.MANV
	where THANNHAN.MA_NVIEN is null and TRPHG = @MaTP
end
exec bai2_4 '008'
-----------BAI3 CAU 1
INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
VALUES('7','DEMO','008','2020-06-10')

create proc SP_INSERTPB
	@MAPB INT, @TENPB NVARCHAR(15),
	@MATP NVARCHAR(9), @NGAYNHANCHUC DATE
AS 
	BEGIN
		IF(EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG = @MAPB))
			PRINT 'THEM THAT BAI'
		ELSE
			BEGIN
				INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
				VALUES(@MAPB, @TENPB, @MATP, @NGAYNHANCHUC)
				PRINT 'THEM THANH CONG'
			END
	END

EXEC SP_INSERTPB '8','CNTT', '008', '2022-1-12'
--------------------------BAI3 CAU 2
create proc SP_UPDATEPB
	@MAPB INT, @TENPB NVARCHAR(15),
	@MATP NVARCHAR(9), @NGAYNHANCHUC DATE
AS 
	BEGIN
		IF(EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG = @MAPB))
			UPDATE PHONGBAN SET TENPHG = @TENPB, TRPHG = @MATP, NG_NHANCHUC = @NGAYNHANCHUC
			WHERE MAPHG = @MAPB
		ELSE
			BEGIN
				INSERT INTO PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
				VALUES(@MAPB, @TENPB, @MATP, @NGAYNHANCHUC)
				PRINT 'THEM THANH CONG'
			END
	END
EXEC SP_UPDATEPB '8','IT', '008', '2022-1-12'
